apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
